commodity_prices_api:
  url: 'https://quickstats.nass.usda.gov/api/api_GET/'
  params:
    key: '5673B6F3-B58E-3FAF-85EB-73050365D958'
    commodity_desc: 'CORN'
    statisticcat_desc: 'PRICE RECEIVED'
    agg_level_desc: 'NATIONAL'
    state_alpha: 'US'
    year__GE: '2010'
    format: 'json'

crop_data_url: 'https://quickstats.nass.usda.gov/api/api_GET/'
crop_data_params:
  key: '5673B6F3-B58E-3FAF-85EB-73050365D958'
  commodity_desc: 'CORN'
  statisticcat_desc: 'YIELD'
  year__GE: '2010'
  format: 'json'
